Repository laminas/laminas-cli, pull requests merged in 2020-04, with the labels that each got.

#13 Fixes value for project config in MkDocs conifguration
  mkdocs.yml
Labels: Bug, Documentation

#12 Lazy load commands
  .travis.yml
  phpcs.xml
  phpunit.xml.dist
  src/ContainerCommandLoaderNoTypeHint.php
  src/ContainerCommandLoaderTypeHint.php
  src/LazyLoadingCommand.php
  test/ContainerCommandLoaderTest.php
  test/LazyLoadingCommandTest.php
  test/TestAsset/ExampleCommandWithDependencies.php
  test/TestAsset/ExampleCommandWithDependenciesFactory.php
  test/TestAsset/ExampleDependency.php
  test/TestAsset/config/application.config.php
Labels: Enhancement

#18 Passing application to lazy loaded command
  src/LazyLoadingCommand.php
  test/LazyLoadingCommandTest.php
  test/TestAsset/ExampleCommand.php
Labels: Bug
